name: Django Pipeline

on:
  push:
    branches: [ main, develop, feature/** ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Baixa o código do repositório
      - name: Checkout do código
        uses: actions/checkout@v4

      # 2. Configura Python 3.12
      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      # 3. Instala dependências
      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Aplica migrações do banco
      - name: Aplicar migrações do banco
        run: |
          python manage.py migrate

      # 5. Roda os testes automáticos
      - name: Executar testes
        run: |
          python manage.py test

      # 6. Executa o servidor Django  
      - name: Executar servidor Django
        run: |
          nohup python manage.py runserver 0.0.0.0:8000 &
          sleep 10
          echo "Servidor Django iniciado com sucesso ✅"
